/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bodoh69.wiiu.titles;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class App {
    static final char[] HEX = {'0', '1', '2', '3', '4', '5', '6', '7',
            '8', '9', 'a', 'b', 'c', 'd', 'e', 'f'};

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String... args) throws Exception {
        Path path = Paths.get("title.list");
        if (! path.toFile().exists()) {
            System.err.println("Cannot find title.list");
            System.err.println("Current directory: " + System.getProperty("user.dir"));
            System.exit(3);
        }
        Titles titles = Titles.selfInit();
        byte[] data = Files.readAllBytes(path);
        if (data.length % 8 != 0) {
            System.err.print("Invalid file size (must be in 8 byte chunks)");
            System.exit(5);
        }
        char[] titleHex = new char[16];
        for (int i = 0; i < data.length; i += 8) {
            Hexer.write(data, i, 8, titleHex, 0);
            String titleId = String.valueOf(titleHex);
            Title title = titles.lookup(titleId);
            if (title == null) {
                System.out.println(titleId + " - not found");
            } else {
                System.out.println(title.getTitleId() + " - "
                        + title.getName() + " - "
                        + title.getType());
            }
        }
    }
}
